### ISSUE TITLE
CSV retrieval much slower than JSON for many rows.

### ISSUE THREAD

**Issue by mikedarcy** [informatics-isi-edu/ermrest#106]
360K rows less than 1MB/sec via loopback, with or without HTTPS.

**Comment by karlcz** [comment]
It seems this is due to using Python to do the CSV serialization of each row, rather than delegating it to postgres like we do for JSON responses.

The wrinkle here is that we cannot use the `COPY ... TO STDOUT WITH CSV` because that requires a writable file descriptor while WSGI and web.py require us to return or yield result text. Using the psycopg2 `copy_expert` method will block until the whole response is written to the descriptor with no opportunity to yield and coroutine with the web framework.

**Comment by karlcz** [comment]
I just committed a temporary-file based hack for this in ermrest/master.  It only accelerates GET requests for text/csv content on the data APIs.  Please give it a try.

**Comment by mikedarcy** [comment]
This fix works well enough for my current use case.  A bag export with approximately 20MB of CSV files which previously took 97sec now takes 16sec.  

Even though this fix essentially requires two writes to disk of the same data(since ermrest and ioboxd are colocated), I think this is reasonable enough trade-off for the near term, at least for my use case.  I am not dealing with massive tabular data exports, so I don't expect to run into any scalability issues any time soon.

Should I close the issue out or keep it open?

**Comment by karlcz** [comment]
close it...

also, try using HTTP instead of HTTPS for your export service case over loopback interface.

**Comment by mikedarcy** [comment]
Switching to HTTP shaved ~1sec off of the 16sec transfer of the same test bag, and consumed significantly less CPU.
