### ISSUE TITLE
include more column types in the '*' textual psuedo-column

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/ermrest#109]
We need to decide what kind of text matching a user expects to succeed when searching tables based on substring search.
- Domains over text
- ISO dates?
- Month names or days of week from dates or times?
- Numerical types and timestamps matched as decimal ascii?
- JSON content?  If so, how?  Full JSON serialization as text?  Just keys and values?

Another issue is that the `*` psuedo column doesn't know anything about column hiding in Chaise. Is this a problem?  Or is it OK to show rows as matching even when the user cannot see the content?

**Comment by karlcz** [comment]
I'd like to work on this soon, but haven't seen any input on how broadly to attack it.  I think we should initially choose between two approaches:

1. Only add domains based on text types to the current behavior.
2. Aggressively cast most types to text and include them.

I lean towards the first option.  The second opens too many possibilities for weird behavior where casting rules aren't going to satisfy user expectations or newly added types introduce new bugs.

**Comment by karlcz** [comment]
The introspection is improved in 45ddb1c0c144128225c0bd48a3084111fe60606e so that the base type of arrays and domains is consistently represented and we can consider the base type when deciding if a column is text-like for indexing.

This still has the same limitation as before in that it only introspects a domain over scalar type or domain over array type.  We do not yet support recursive introspection to walk domains defined over other domains.

@hongsudt @ljpearlman @bugacov  you should be able to test by rebuilding value map or freetext indices with the latest code and seeing that columns with text domains like markdown are now included.

**Comment by karlcz** [comment]
Is anybody going to review this or should I just close it?
