### ISSUE TITLE
If-Match header fails when etag matches existing etag

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/ermrest#112]
When making an update to an entity, a `412 Precondition Failed` error is returned. It appears that ermrest is not matching the etag properly.

**Comment by karlcz** [comment]
This seems to have involved two different problems...
1. The whole client object rather than just ID was being baked into ETags and might not be a stable representation. I changed it to pluck out just the ID field.
2. The mod_deflate module enabled on the dev server is mangling the ETag and adding a `-gzip` suffix inside the service-generated ETag. So, went sent back by the client it would never match the service-internal ETag.  I changed our parser to remove the `-gzip` part and get back to our canonical form.

@jrchudy already confirmed that it now works for him, so I am closing this.
