### ISSUE TITLE
Internal error for POST entity API with all columns as defaults

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/ermrest#120]
When a POST request is generated where all the columns of the table are included in the defaults list, a 500 internal server error is returned.

**Comment by karlcz** [comment]
I refreshed myself on this topic and I don't think there really is any appropriate solution to accept N rows of input and ask for all columns to be populated by default values. This is a SQL limitation I don't want to try to work around in the service logic.

So, I think I'm just going to fix the server to raise a 409 Conflict if the request includes all columns of the schema in the defaults list (rather than an internal server error).

**Comment by karlcz** [comment]
This is in master as https://github.com/informatics-isi-edu/ermrest/commit/67d366281498f5fb919c81974cc11aea99913def  with a basic test case.

@jrchudy if you can easily reproduce in your test environment, please do. But if not, I think this test case already covers the reported issue and we can just close this...
