### ISSUE TITLE
Don't check referential integrity constraint when using explicit join predicate

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/ermrest#125]
Something to consider...

ERMrest currently allows joins in its 'paths' only when there is a foreign key referential integrity constraint between tables. The constraint was needed when it only supported implicit joins between tables but now that ermrest has the explicit join predicate expression it could allow joins even when no foreign key references are defined in the model. This would allow exploratory use cases and support databases that are in an earlier 'messy' state.

**Comment by karlcz** [comment]
It could, but model-driven clients like Chaise wouldn't know how to formulate such ad hoc joins...

You can use (or abuse) the pseudo-key and pseudo-foreign key mechanism to similar effect to make arbitrary joins but also advertise these to model-driven clients.

**Comment by karlcz** [comment]
@robes 

So do you really have a need for ad hoc queries, independent of the Chaise front-end?  Or can you use the pseudo constraint feature to define your joining patterns and also advertise them to Chaise?

**Comment by karlcz** [comment]
@robes  This is funny, but actually the service already behaves as you requested and it is even documented that way but we both forgot about it!

https://github.com/informatics-isi-edu/ermrest/blob/master/api-doc/data/naming.md#linkage-by-explicit-column-mapping

This reads in part, "Because it fully expresses an unambiguous join condition, it does not require a corresponding foreign key reference link to be found in the catalog model."
