### ISSUE TITLE
support substring search on int, float, and date columns

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/ermrest#130]
Currently, the search can only be done on text columns. Can we expand it to the above types? From the UX perspective, they probably don't care whether the columns are represented as numbers of text..

```
select 20170101::text;  -> 20170101
select 201.70101::text;  -> 201.70101
select '20170101'::date::text; -> 2017-01-01
```

**Comment by karlcz** [comment]
We can do this with some caveats

1. The `*` psuedo column feature applies equally to regexp and full-text search operators. The result of putting all these digit strings into the text search vector may be odd, depending on how the stemming and such goes.
2. Making this change will disrupt all existing deployments, making their existing text indices obsolete and causing all new searches to be brute-forced until the indices are rebuilt using the latest utility script that will go with the service update. (This indexing is not automatically performed.)
3. We chose to limit the input types previously out of concern for the UX that will happen here.  You'll really get substring match on these strings, rather than anything based on numerical magnitude or precision. With floating point numbers that look "irrational" as decimal, you will get a lot of substring matches due to all the digit combinations...

**Comment by karlcz** [comment]
Another caveat is that timestamps will have to be converted to a deterministic text format for search in order to allow expression indices to be built. We'll use ISO 8601 format for all time, timestamp, and date columns for simplicity.  A user will have to use UTC time if they really want to search for an hour substring...

**Comment by karlcz** [comment]
This is pushed to master in 9c2c38002142ca25a9ae19627742bb781b29673b and includes test cases.

**Comment by karlcz** [comment]
I'm closing this as I think the requested feature is done and in use.  But there is a related PR #132 pending which fixes problems encountered on some deployments and extends the test suite for more column types.
