### ISSUE TITLE
api for column summary e.g. histogram

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/ermrest#134]
* For ordinal value such as integer, float, date, timestamp, what about we use min, max, number of bins as parameters? The problem is what do we do with the null value..
 

New feature documented as [Attribute Binning](https://github.com/informatics-isi-edu/ermrest/blob/master/api-doc/data/naming.md#attribute-binning) in the latest ERMrest api docs.

**Comment by karlcz** [comment]
This is essentially a histogram over a single `/attribute/...entitypath.../filter/column` right?  I.e. the client may have a complex query to reduce the set of entities and then we want a histogram of one column from that set of entities.

Should the min and max be optional, in which case the server has to figure it out?

Should values outside the min and max range be discarded or accumulated into first/last bins?

Do you expect to have a search UI where you would allow selection of null as a filter?  If so, I can see having a separate null bin.  If not, I think you'd want to exclude nulls from the totals and only talk about the distribution of values which can act as a facet.

**Comment by karlcz** [comment]
There is a built-in postgres function `width_bucket()` which might be the right thing to use here.  It has two calling conventions:

1. For numeric sample types it can take a half-open interval boundary `[lower,upper)` and a number of steps N to divide that interval into bins, and calculates the bin number for a given sample value.
    - works natively for integer, float
    - we can apply it to dates or timestamps with an appropriate expression e.g. to convert into epoch time values or similar
2. For any ordered sample type (postgres `anyelement` polymorphism) it takes an N-length array of bin lower bounds and determines the bin number for a given sample value.
    - could apply to additional types like `text`

If we want the server to do the work, it would have to determine the min and max value for the range as separate queries and then feed that into the final histogram query.  If we want the client to control it, we need a syntax allowing for the client to specify bounds in the URL.

We have to decide whether to make this a separate API or just a special projection mode that lets us access something like the bucket function as a grouping key.  The results would be one row per bin, and should have the bin number and/or bin half-open interval values in it since it may be sparse.  We'll only see an output bin if at least one sample falls within the bin.  An advantage of doing it as a projection is that we could add other kinds of group key projection later, such as precision truncation operators for timestamps, e.g. day/week/month/year groupings.

I don't think paging or sort really make sense for this API, but it's relatively harmless (just slow) to expose it via the attributegroup API and just tell clients not to code stupid requests...?

**Comment by karlcz** [comment]
It looks like the polymorphic width_bucket function was first added in postgres 9.5 so we won't be able to use that and test in our current travis builds unless we move them forward from 9.4 which they currently use in testing.

**Comment by karlcz** [comment]
This is pushed to master for basic numerical column types and where the client must explicitly specify the number of bins and min/max of the value range they wish to analyze.

**Comment by karlcz** [comment]
@hongsudt this wasn't reviewed before @RFSH went on break.  can someone else review the ermrest feature?

**Comment by karlcz** [comment]
@RFSH @jrchudy have you guys played with the histogram api enough to close this ermrest review issue...?

**Comment by karlcz** [comment]
A bug was found in reviewing this... the result bins were labeled with incorrect descriptive boundary values, even though correct boundaries were used to actually assign the rows to bins.  A fix for this, as well as generalization of the feature to support timestamptz and date column types has been pushed to master and also merged to the acls-everywhere branch.

**Comment by jrchudy** [comment]
After the recent fix you made @karlcz, binning seems to work a lot more appropriately. Now, as I increase the number of bins without changing the interval, I see that the bin ranges are changing appropriately.

For example, I have `bin(int;9;10;100)`, I see bins being returned as `[0, null, 10]`, `[1, 10, 20]`, and `[10, 100, null]`. I also only see bins that had values in it. So in my example, I didn't see bins for some ranges that I had no values for the ranges `40-50` and `70-80`.

I verified this works for my foreign key columns as well when it has an integer or a serial. And verified that it works for `date` and `timestamptz` columns.
