### ISSUE TITLE
PUT attributegroup silently fails when blocked by Postgres row-level security

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/ermrest#142]
When a PUT request is made to `ermrest` with data changed, no data is returned in the corresponding response. I noticed this on the gpcr dev machine.

[This](https://dev.gpcrconsortium.org/chaise/recordedit/#1/assets:cpm_file/id=111) is the entity I was editing. I appended `- test` to the existing title, represented by `title_n` and `title_o` below. This request returns a 200 Status Code in the response but there is no corresponding data. I verified that this row is not actually updated in the database.

From the api.doc for attribute group update:
`On success, the response contains updated row information`

**General Info:**
`Request URL: https://dev.gpcrconsortium.org/ermrest/catalog/1/attributegroup/assets:cpm_file/id_o:=id,site_name_o:=site_name,cpm_accession_id_o:=cpm_accession_id,sample_accession_id_o:=sample_accession_id,cpm_format_o:=cpm_format,number_of_samples_o:=number_of_samples,title_o:=title,config_o:=config,filename_o:=filename,filesize_o:=filesize,uri_o:=uri,sha256_o:=sha256,user_folder_o:=user_folder,creation_timestamp_o:=creation_timestamp,last_modified_timestamp_o:=last_modified_timestamp;id_n:=id,site_name_n:=site_name,cpm_accession_id_n:=cpm_accession_id,sample_accession_id_n:=sample_accession_id,cpm_format_n:=cpm_format,number_of_samples_n:=number_of_samples,title_n:=title,config_n:=config,filename_n:=filename,filesize_n:=filesize,uri_n:=uri,sha256_n:=sha256,user_folder_n:=user_folder,creation_timestamp_n:=creation_timestamp,last_modified_timestamp_n:=last_modified_timestamp?cid=recordedit
Request Method: PUT
Status Code: 200 `

**Request Data:**
`config_n: null
config_o: null
cpm_accession_id_n: "GPCRUSC20170314CPM2"
cpm_accession_id_o: "GPCRUSC20170314CPM2"
cpm_format_n: "interleave"
cpm_format_o: "interleave"
creation_timestamp_n: "2017-03-14T15:40:54.390626-07:00"
creation_timestamp_o: "2017-03-14T15:40:54.390626-07:00"
filename_n: "Front End Test_Intensity.csv"
filename_o: "Front End Test_Intensity.csv"
filesize_n: 8523
filesize_o: 8523
id_n: 111
id_o: 111
last_modified_timestamp_n: "2017-03-14T15:45:03.000-07:00"
last_modified_timestamp_o: "2017-03-14T15:45:03.498899-07:00"
number_of_samples_n: 4
number_of_samples_o: 4
sample_accession_id_n: null
sample_accession_id_o: null
sha256_n: "bfbebfacc4e11c69b41f358143171271306eac9544779c02347e8ea71b32611a"
sha256_o: "bfbebfacc4e11c69b41f358143171271306eac9544779c02347e8ea71b32611a"
site_name_n: "USC"
site_name_o: "USC"
title_n: "Intensity - test"
title_o: "Intensity"
uri_n: "/hatrac/assets/USC/cpm/2017/01/78f585c2ff5e597f80c67e72e40275ea2644a0861d334b1087FrontEndTest_Intensity.csv"
uri_o: "/hatrac/assets/USC/cpm/2017/01/78f585c2ff5e597f80c67e72e40275ea2644a0861d334b1087FrontEndTest_Intensity.csv"
user_folder_n: "test"
user_folder_o: "test"`

**Comment by karlcz** [comment]
@jrchudy do you have any simpler error case?  this one includes a fair number of oddities including the use of timestamp columns as correlation keys and a table involving row-level security on a test server.

**Comment by karlcz** [comment]
I'm pretty sure this is due to row-level security and really can't be solved in a reasonable way by ermrest.  If the DBA has enabled row-level security on a table and the policies are blocking row updates, postgres will return a success with fewer rows updated (basically hiding rows during the the UPDATE statement).

In your front-end, you know you are trying to update exactly one row and so should just interpret this zero row response as if it were Forbidden.  Ermrest isn't clever enough to do this for you because the PUT attributegroup API covers a lot more general one-to-many update scenarios than just this exact update of one row.

Once the new acls-everywhere branch gets merged, we will have a fine-grained authz mechanism which can efficiently return a Forbidden in this case. Once we migrate to that, we'll deprecate use of Postgres row-level security and this particular problem will go away.  But that is months away...
