### ISSUE TITLE
check there is at least one not null unique constraint per table

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/ermrest#144]
If not, return an error..

**Comment by karlcz** [comment]
A wrinkle here is SQL views.  We currently have a notion of pseudo-keys and pseudo-foreign-keys so the DBA can tell us how a view behaves and present that to the ERMrest client.  We don't have a notion of pseudo-not-null constraints.  So, views will still appear to ERMrest clients as if they have all nullable columns, even if the DBA wrote a view that they know cannot produce nulls for some columns.

If we're trying to make a new interface invariant that every entity set in ermrest has a primary key, we'll also need pseudo-not-null and need to require this of all views as well as all tables.

**Comment by karlcz** [comment]
@hongsudt is this a priority right now?  I don't think we're blocked on it, are we?

**Comment by karlcz** [comment]
This is implemented in latest master.  The following errors will be reported when strict checking is enabled:

- 500 error if introspection of catalog finds a table or view w/o a not-null key
- 400 error if a create table request lacks a not-null key
- 409 error if a key removal would remove the last not-null key on a table or view

These checks can be disabled in a deployment by setting the non-default setting:

    "require_primary_keys": false

which is set to `true` in the new sample config and defaults to `true` when not included in a legacy config file.

**Comment by karlcz** [comment]
@hongsudt  I don't know who needed this or who can review its functionality... it passed my own testing.

**Comment by hongsudt** [comment]
@ljpearlman can you please help review this issue?

**Comment by ljpearlman** [comment]
I can verify that the model_pseudo_notnull annotation works and that any attempt to access an object in a database that contains any object without a non-null unique key generates a 500 error. It's not entirely clear to me from the issue description whether that was @hongsudt's intention when creating this issue, or whether it was supposed to give a 500 error only when trying to access an object without a non-null unique key. It also seems a little odd to me that the two options are to not check at all or to fail catastrophically; a "check and give a warning" option would be nice.

**Comment by ljpearlman** [comment]
It turns out that, if there's a table/view missing a non-null unique key, ermrest will respond to queries successfully for a while and then later start failing on every query. Again, I'm not sure what it's supposed to be doing, but without a way to test that a database is compliant and get a definitive "yes" answer, I'm not sure what the value of this feature is.

**Comment by karlcz** [comment]
The check is done when it introspects the DB schema.  It caches the
introspection until the model_change_event() occurs or the daemon
process restarts, whichever comes first.

The only way I can see explain this failure mode is if you changed the
DB schema while the service was running, did not issue
_ermrest.model_change_event() to notify ermrest that it changed, and
eventually ermrest recycled one or more daemon processes which then
had to introspect the schema again.

All such changes to schema should be done transactionally and include
the model_change_event() call in the same transaction.

**Comment by ljpearlman** [comment]
I suppose it's possible someone else did something overnight, but all our scripts are transactions that include model_change_event().

**Comment by karlcz** [comment]
Also, if you migrate any catalog from one DB to another e.g. via SQL
dumps and restores, you will corrupt the internal version tracking
such that model_change_event() and data_change_event() do not function
correctly.

To fix it, you need to truncate the two version tracking tables in
the _ermrest schema if you've copied that schema from another DB, e.g.

    TRUNCATE _ermrest.model_version;
    TRUNCATE _ermrest.data_version;

otherwise it may have mismatching transaction ID information from the
old DB while the new one has unrelated transaction IDs.  This is a
known issue in ERMrest and won't be resolved unless we replace the
whole version tracking scheme with one that does not involve the DB
transaction IDs.

**Comment by ljpearlman** [comment]
Yeah, we do that. This particular case doesn't involve moving catalogs, though.

**Comment by karlcz** [comment]
I pushed a small enhancement to make it always check for primary keys during introspection. Now, the config value controls whether an internal server error is raised (enforcing mode) or a warning is just logged to the httpd error log (e.g. ssl_error_log in typical deployments).  Previously, it was completely silent when enforcement was disabled.
