### ISSUE TITLE
Foreign key policy decision bug

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/ermrest#184]
Enforcement of foreign key update does not appear to be inheriting acl binding from enclosing table.

Example:
- At the table level, 
  - static Insert is allowed for a user GroupA
  - dynamic acl for Update allowed for certain users (based on a projection not described here)
- the foreign keys of this table,
  - have no acl or acl_binding documents, and therefore should be *unrestricted*

Expected:
- if a user can update a row of this table, they should be able to set the foreign key to any valid domain value

Observed behavior:
- `Error 403 Forbidden The requested update access on foreign key reference :isa:sample:specimen=@:vocabulary:specimen:id is forbidden.`

**Comment by karlcz** [comment]
I've revised the issue title.  It may not be inheritence of an acl binding, but just an incorrect static policy decision.

We need to trace this through a little more with your failure scenario, but I suspect this is actually a bug in the static policy decision layer.  I think it may be incorrectly deciding that we have a data-dependent policy scenario when it was really supposed to be a static grant, and then the data-dependent checks fail because there aren't any applicable acl bindings.

**Comment by karlcz** [comment]
@robes  Surprisingly, it seems to me that this may have been broken since 2017-06 when [this commit deleted these lines](https://github.com/informatics-isi-edu/ermrest/commit/62d42b569dd17a631bafa129d2476a5586d71b54#diff-167bbde9647a3f99c865ee743aa8e509L492) which were implicitly filling in default permissive FKR policies.

I think I was mistaken in removing that default. But, I wonder if anybody else now depends on that broken behavior...

**Comment by karlcz** [comment]
Closing this since the fix works for you.  But the PR merge is still waiting for @ljpearlman  to test on her complex policy example...
