### ISSUE TITLE
Strange interaction between pseudo-keys and static ACLs?

### ISSUE THREAD

**Issue by ljpearlman** [informatics-isi-edu/ermrest#194]
Note: the view we're looking at currently exists only on hosts running the master branch, so I don't know whether this issue exists in stateful-model (@hongsudt, it might be helpful if you created the dashboard views on rbk-dev so we could check this out on the stateful branch).

We have a view (Dashboard:Monthly_Submission_Dashboard) with a static ACL that restricts select and write access to a list of groups (the parent schema has no ACLs). When you're logged in to one of the groups that has permissions, the unique constraint on the RID column is visible:
```
  "keys": [
    {
      "comment": null, 
      "unique_columns": [
        "RID"
      ], 
      "annotations": {}, 
      "names": [
        [
          "", 
          4814
        ]
      ]
    }
  ],
```
When you examine the schema anonymously, it isn't:
```
  "keys": [], 
```

(you do see "nullok": false in both places, though).

You can see the table definition at https://staging.rebuildingakidney.org/ermrest/catalog/2/schema/Dashboard/table/Monthly_Submission_Dashboard

**Comment by karlcz** [comment]
I think this is because we exclude constraints that depend on columns you cannot access.

If you were to set a static "select": ["*"] ACL on the RID column, I
think the key would become visible even to anonymous users who have no
access to individual rows.

**Comment by ljpearlman** [comment]
We're not doing row-level access control; we want anonymous chaise users who try to access the table to be prompted to log in, so at the table level we have this:
```
"acls": {
    "write": [
         (some globus ids)
    ],
    "select": [
         (some globus ids)
    ]
},
...
"acl_bindings": { },
```
Just for completeness, I went ahead and added the column-level permission you suggested:
```
{
    "name": "RID",
     ...
    "acls": {
        "select": [
            "*"
        ]
    },
    "acl_bindings": { },
    ...
}
```
and anon users still don't see the key.

**Comment by karlcz** [comment]
Sorry, I misunderstood the scenario.

I think both branches behave the same way, and indeed it is because we
exclude constraints that involve columns which cannot be selected.
This is an extreme corner case where nothing can be selected.  The
exclusion is more significant when some columns are selectable and we
want to show the client the subset of relevant constraints for their
access level.

My previous suggestion was useless because I forgot that we also
consider row-level access when determining column rights, so in this
case the select rights remain false on each column since they are
false on the table as a whole.  I don't think there is any way to get
the behavior you want, which is to report the whole table as
statically non-selectable while also listing its keys.

I am inclined towards saying the real problem here is in Chaise
blundering ahead when the rights summary clearly tells it that it
won't have permission.  In reality, it needs to perform the login
flow, get a revised model (and rights summary) for that logged in
user, and then restart its app flow.  The fact that it is rushing into
"unsafe" query paths before the login flow has completed seems like a
sequencing flaw to me.
