### ISSUE TITLE
More permissive "=" definition for ermrest_rid type

### ISSUE THREAD

**Issue by ljpearlman** [informatics-isi-edu/ermrest#195]
We use RIDs as part of the filesystem path template for the the gudmap uploader, and @hongsudt asked if I could make those case-insensitive. I can rewrite the templates to use ::cigregexp:: with anchored regular expressions, but it would be nice to also be able to handle O and I (or l) for 0 and 1 without hideously ugly regexes. It would also be nice if ermresolve allowed for the same kind of permissive matching. It seems like the most sensible way to implement this would be to change the definition of the = operator for the ermrest_rid datatype at the ermrest or postgres level.

**Comment by karlcz** [comment]
I think we could normalize the RID literals from the URL used in an `=` filter against an ermrest_rid column.

However, this will not happen for foreign keys to RIDs since the referring column is text, not ermrest_rid.  If this is important, I think we'd need to add another domain like ermrest_rid_ref or something to distinguish those referring columns.

And even then, this normalization is not possible in regexp searches including the search box behaviors in chaise.  I think those do case-insensitive search in Chaise, but they will obviously not introduce appropriate character classes like `[0Oo]` and `[1iIl]` since there is no way to know when a RID is being attempted.

**Comment by karlcz** [comment]
A subset of this feature has been added.  It does not know about `ermrest_rid` type (which is proposed to be deprecated in #204) but works for `RID=` _value_ filters and also for the new `/entity_rid/` _value_ API to attempt to normalize the _value_ for comparison.

**Comment by karlcz** [comment]
I'm closing this, because I don't think any further enhancement is anticipated...
