### ISSUE TITLE
don't enforce constraints on temporary input table

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/ermrest#208]
The table has a not-null constraint on a data column that is populated by a trigger. Ermrest needs to ignore the constraint so the request can be processed. 

Here is the snippet of the error code:
```
'  File "/usr/lib/python2.7/site-packages/ermrest/ermpath/resource.py", line 474, in _load_input_data_json\\n    \\'json_proje
```

**Comment by karlcz** [comment]
Investigating this further, I think this is really a client misbehavior.  In this request, Chaise is expecting the server to populate the `Title` column but did not include it in the `defaults` query parameter.

I think this is only an issue because of your peculiar scenario which cannot occur with normal use of the ERMrest apis:
1. The column is set `NOT NULL`
2. The column has a NULL default
3. The column is not being set by the client
4. There is a SQL trigger to populate the column before it hits the table and violates the NOT NULL constraint

Normally, the first three items would cause a client error. The introduction of the trigger fixes it by generating a value.

But, ERMrest doesn't accept this because it validates the NOT NULL constraint on its temporary input table holding the client request content, so it can rely on this property when forming the eventual insert or update statements it performs on the storage table. By relying on these properties, we generate better performing SQL with better error responses for normal REST clients.  This non-null property is only significant for our queries involving user-supplied values, so we already skip validation when columns are in the `defaults` parameter and we know the client input is going to be ignored.

As I understand it, Chaise has dropped the column from the `defaults` using a heuristic intended to prune this list when sending a client-supplied `null` is expected to produce the same result, i.e. when the column introspection indicates a default of `null`.  We have agreed to tighten this heuristic as a workaround, so that ERMrest does not need to water down its content validation for all clients.
