### ISSUE TITLE
Default key and foreign key names

### ISSUE THREAD

**Issue by ljpearlman** [informatics-isi-edu/ermrest#214]
If no constraint name is specified when creating keys or foreign keys, ermrest generates constraint names that use a number as a suffix (e.g., "table_column1"), while our "best practice" is to use "_key" and "_fkey" as suffixes (e.g., "table_column_fkey"), presumably with a number tacked on to the end if necessary to avoid collisions.

(My possibly-hazy memory is that the "just a number" suffix was a deliberate decision to deal with identifier length limitations in Postgres. If that's the case, then I'd accept as alternate solutions either a) adding more complicated length-based logic or b) convincing @hongsudt and @carlkesselman that having key/fkey  names without `_key` or `_fkey` is not a problem).

**Comment by karlcz** [comment]
I think this was addressed in #228 but we forgot to close the issue.

Since then, the service attempts to compose a list of table + colnames + suffix where the suffix is `key` or `fkey` as appropriate, but will also add a numeric suffix to resolve collisions. E.g. `key2` or `fkey2`.

It also added heuristics when the naive formula of table + colnames + suffix produces a string that is too long for an identifier. It attempts several strategies to shorten the string while preserving some human-readable content, including:
- truncating individual long consituent table or column names
- trimming out the middle section and adding a hash suffix
- last-ditch truncation of naive result and replacement with a hash suffix

Only in the last-ditch case will the result lack the `_key` or `_fkey`  substring near the end of the identifier. This is unlikely to occur unless the table and column names use multi-byte UTF-8 codepoints and the truncation logic fails to find an appropriate split.  (The postgres identifier length limit is in the number of encoded UTF-8 octets, not a fixed number of unicode characters.)
