### ISSUE TITLE
History breaks when ACLs depend on columns the user can't see

### ISSUE THREAD

**Issue by ljpearlman** [informatics-isi-edu/ermrest#222]
RBK/GUDMAP policies depend on the value of a column called "Curation_Status", which itself is not visible to anonymous users (for an example, see https://www.gudmap.org/ermrest/catalog/2/schema/Cell_Line/table/Mouse_Strain). Attempts to view historic versions of these records (e.g. https://www.gudmap.org/ermrest/catalog/2@2SB-GG8E-SAN0/entity/Cell_Line:Mouse_Strain/RID=Q-2CPT) result in errors like this:

```
409 Conflict
The request conflicts with the state of the server. column t0.Curation_Status does not exist
LINE 9:  t0 WHERE ((t0."Curation_Status" = 'Release'::text AND t0."C...
```

There isn't any actual need for secrecy for the Curation_Status column; it's hidden from anonymous users to keep their display uncluttered (while still showing that column to privileged users, who do want to see it).

**Comment by karlcz** [comment]
Hmm, do you have evidence that this is specific to accessing historical snapshots? Or is this just the scenario you encountered, but it might be because the snapshot contains a different arrangement of policies than current, live data?

**Comment by karlcz** [comment]
I think I understand this now, and it is specific to history access. In this case, the table source is a subquery projecting out the variousfields from the JSON-based history storage. These subqueries are a stand-in for the raw table name used in live catalog access.

These stored fields are named by column RID and have to be projected back into their expected names for the model known at the time of the snapshot. The code doing that is using a method which observes the per-column `enumerate` rights.

I think the fix for this is quite small, but it will need some testing and review...

**Comment by ljpearlman** [comment]
I still want to do some more testing, but so far it looks good -- the effective permissions for a snapshot appear to be the permissions that were in effect at the time. I'm wondering whether that's completely optimal (someone who accidentally makes something readable and then fixes it a minute later might not realize the historic version is still exposed), but that's a hairier philosophical question beyond the scope of this issue.

**Comment by karlcz** [comment]
That's what history amendment is for... the admin can, in theory,
modify policies (and annotations) retroactively to change presentation
of historical tuples.

But as a default case, there's no reliable way for ermrest to assume
when a live change should be applied retroactively or not.  (Nor even
whether such a change is entirely valid, since history includes model
as well as data changes.)

**Comment by karlcz** [comment]
I think we can close this, unless your testing has found any further problem?
