### ISSUE TITLE
How to test the API using curl

### ISSUE THREAD

**Issue by rjiang9** [informatics-isi-edu/ermrest#254]
Hi Folks, 

In the API doc, there is a piece of code like this:

```
POST /ermrest/catalog/42/schema/schema_name/table HTTP/1.1
Host: www.example.com
Content-Type: application/json

{
  "schema_name": schema name,
  "table_name": table name,
  "comment": table comment,
  "annotations": {
    annotation key: annotation document, ...
  },
  "column_definitions": [ column representation, ... ],
  "keys": [ key representation, ... ],
  "foreign_keys": [ foreign key representation, ... ],
  "kind": "table"
}
```
My questions, if using `curl` to make the call, what is the correct format? I tried: 

```
curl -k -b cookie -X POST --header "Content-Type: application/json" --data '{ "schema_name": "ray","table_name": "table2","comment": "comment2", "column_definitions": [colum1, colum2], "kind": "table"}' "https://derivar.rcs.ucalgary.ca/ermrest/catalog/21/schema/ray/table"

```
I ran into issues with the errror message:

`Request malformed. Detail: Could not deserialize JSON input.`. I did once and it passed but I forgot how I did.

Thanks,
Ray

**Comment by rjiang9** [comment]
By the way, in the doc, it looks you can copy and paste the test code, what is the tool you use?

**Comment by karlcz** [comment]
Note, we would recommend using the deriva-py Python client library to 
manage catalog schemas etc. rather than curl. But, I think you could 
replace --data with --json in your example so that curl will send it as 
JSON rather than trying to do http form data encoding.

See 
https://github.com/informatics-isi-edu/deriva-py/blob/master/docs/project-tutorial.md 
for a tutorial overview of setting up a project-specific catalog using 
deriva-py.

Also, 
https://github.com/informatics-isi-edu/deriva-py/tree/master/docs#ermrest-model-management 
has a bit more terse summary of some model management tasks.

**Comment by rjiang9** [comment]
Thank you very much for your reply, Karlcz! @karlcz we are going to try out your recommended way for doing it.
