### ISSUE TITLE
Modify ermrest/hatrac ACL to support the new webauthn

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/ermrest#60]
- ERMrest
  - [ ] ~~Adjust the ACL storage schema for new catalog deployments as needed~~
  - [x] Adjust internal code that intersects ACLs with webauthn.context.attributes
  - [x] Adjust internal code that exposes webauthn.context as PostgreSQL session parameters for row-level security scenarios
  - [ ] ~~Update row-level-security documentation to reflect examples using new session parameters and recommended storage representation for security identifiers/attributes in application schemas~~ There are no changes for application schemas.
- Hatrac
  - [ ] ~~Adjust the ACL storage schema~~
  - [x] Adjust internal code that  intersects ACLs with webauthn.context.attributes
  - [x] Adjust internal code that injects webauthn.context.client into new ownership ACLs

**Comment by karlcz** [comment]
Rather than branching, I patched ermrest/master and hatrac/master to have compatibility with both webauthn/master and webauthn/globus_auth by detecting whether the webauthn API is returning bare strings or dictionaries for the client context values.

The ACL storage needs a little more thought.  I'd like to come up with a similar backwards and forwards compatible code patch to ease transition of existing deloyments. 
1. In ermrest, ACLs are stored in the catalog "meta" table which is a key-value store with `text` type values (with a full ACL spread across multiple rows). If we changed the value type to `jsonb` I could branch on that. But, this would also affect other future use of metadata...
2. In hatrac, ACLs are stored in dedicated columns of type `text[]` containing a full ACL. If we change the ACL type to `jsonb[]` I could branch on that.

**Comment by karlcz** [comment]
After further discussion with @ljpearlman we decided *not* to change ACL storage formats. This opens a lot more questions than it answers and there is no reason to pursue this right now.

**Comment by karlcz** [comment]
Reassigning to @ljpearlman for review.  If she wants to deploy latest master hatrac and ermrest with any permutations of security that she is testing, they should all work.

**Comment by karlcz** [comment]
We're already running this on several servers so I am going to call it done and reviewed.
