### ISSUE TITLE
Draft annotation for rendering column data as link, download, image URLs

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/ermrest#93]
These annotations include 
* navigator links
* download links
* thumbnails
* inline images

From our meeting, we discussed about using a markdown or html as the annotation syntax to capture link and caption. The app needs to make sure that the html is sanitized to prevent code injection.

**Comment by karlcz** [comment]
I think we should split out the two cases currently mangled together in the old URL annotation:

1. Displaying a column of each record as a URL as per above, using templates.
2. Displaying an entire record as a URL, i.e. the current use of the iframe hack

I think this issue is about the first item, and the second item needs its own issue.

**Comment by karlcz** [comment]
This is drafted in https://github.com/informatics-isi-edu/ermrest/blob/master/user-doc/annotation.md#2016-column-display 

The idea is that there are two composable display options:

1. `pre_format` can wire in a format string library to do things like number serialization with precision, pad, and fill settings
2. `markdown_pattern` can interpolate column values together into a markdown text that is used to represent the column value

**Comment by hongsudt** [comment]
This is fine for now, but we need to add explicit syntax on how to do the annotation for the above use case.

**Comment by karlcz** [comment]
Shouldn't this issue be closed now? The draft annotation has been written, reviewed, and already implemented now, hasn't it?
